spring.application.name=jSaga

spring.datasource.url=jdbc:sqlite:./data/jsaga.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

jsaga.print.escpos.enabled=true
jasaga.print.escpos.serial-enabled=true
jsaga.print.escpos.serial-port=/dev/rfcomm0
jsaga.print.escpos.serial-baud-rate=9600
jsaga.print.escpos.serial-data-bits=8
jsaga.print.escpos.serial-stop-bits=1
jsaga.print.escpos.serial-parity=none
jsaga.print.escpos.system-print.enabled=true
jsaga.print.escpos.printer-name=pt-210-bt

